<?php

class campaign
{
    public $campaign_id = "";
    public $campaign_name = "";
    public $campaign_description = "";
    public $user_group = "";
    public $active = "";
    public $park_file_name = "";
    public $web_form_address = "";
    public $allow_closers = "";
    public $hopper_level = "";
    public $auto_dial_level = "";
    public $next_agent_call = "";
    public $local_call_time = "";
    public $voicemail_ext = "";
    public $script_id = "";
    public $campaign_script_two = "";
    public $get_call_launch = "";
    public $web_form_address_two = "";
    public $web_form_address_three = "";
    public $web_form_target = "";
    public $lead_order = "";
    public $lead_order_randomize = "";
    public $lead_order_secondary = "";
    public $list_order_mix = "";
    public $lead_filter_id = "";
    public $drop_lockout_time = "";
    public $call_count_limit = "";
    public $call_count_target = "";
    public $auto_hopper_multi = "";
    public $use_auto_hopper = "";
    public $auto_trim_hopper = "";
    public $hopper_vlc_dup_check = "";
    public $manual_dial_hopper_check = "";
    public $dial_method = "";
    public $dial_level_threshold = "";
    public $dial_level_threshold_agents = "";
    public $available_only_tally_threshold = "";
    public $available_only_tally_threshold_agents = "";
    public $adaptive_dropped_percentage = "";
    public $adaptive_maximum_level = "";
    public $adaptive_latest_server_time = "";
    public $adaptive_intensity = "";
    public $adaptive_dl_diff_target = "";
    public $dl_diff_target_method = "";
    public $concurrent_transfers = "";
    public $queue_priority = "";
    public $drop_rate_group = "";
    public $inbound_queue_no_dial = "";
    public $inbound_no_agents_no_dial_container = "";
    public $inbound_no_agents_no_dial_threshold = "";
    public $auto_alt_dial = "";
    public $dial_timeout = "";
    public $dial_timeout_lead_container = "";
    public $dial_prefix = "";
    public $manual_dial_prefix = "";
    public $campaign_cid = "";
    public $use_custom_cid = "";
    public $cid_group_id = "";
    public $campaign_vdad_exten = "";
    public $campaign_rec_exten = "";
    public $campaign_recording = "";
    public $campaign_rec_filename = "";
    public $allcalls_delay = "";
    public $omit_phone_code = "";
    public $routing_initiated_recordings = "";
    public $per_call_notes;
    public $comments_all_tabs;
    public $comments_dispo_screen;
    public $comments_callback_screen;
    public $qc_comment_history;
    public $hide_call_log_info;
    public $agent_lead_search;
    public $agent_lead_search_method;
    public $clear_script;
    public $clear_form;
    public $user_nickname;
    public $vmm_daily_limit;
    public $waitforsilence_options;
    public $amd_type;
    public $amd_agent_route_options;
    public $cpd_amd_action;
    public $cpd_unknown_action;
    public $amd_inbound_group;
    public $amd_callmenu;
    public $leave_vm_message_group_id;
    public $leave_vm_no_dispo;
    public $am_message_wildcards;
    public $amd_send_to_vmx;
    public $xferconf_a_dtmf;
    public $xferconf_a_number;
    public $xferconf_b_dtmf;
    public $xferconf_b_number;
    public $xferconf_c_number;
    public $xferconf_d_number;
    public $xferconf_e_number;
    public $enable_xfer_presets;
    public $hide_xfer_number_to_dial;
    public $prepopulate_transfer_preset;
    public $quick_transfer_button;
    public $transfer_button_launch;
    public $custom_3way_button_transfer;
    public $three_way_call_cid;
    public $three_way_dial_prefix;
    public $three_way_volume_buttons;
    public $customer_3way_hangup_logging;
    public $customer_3way_hangup_seconds;
    public $customer_3way_hangup_action;
    public $three_way_record_stop_exception;
    public $leave_3way_start_recording;
    public $leave_3way_start_recording_exception;
    public $three_way_record_stop;
    public $hangup_xfer_record_start;
    public $ivr_park_call;
    public $ivr_park_call_agi;
    public $timer_action;
    public $timer_action_message;
    public $timer_action_seconds;
    public $timer_action_destination;
    public $scheduled_callbacks_alert;
    public $scheduled_callbacks_count;
    public $callback_days_limit;
    public $callback_hours_block;
    public $callback_list_calltime;
    public $callback_active_limit;
    public $callback_display_days;
    public $callback_dnc;
    public $my_callback_option;
    public $show_previous_callback;
    public $callback_useronly_move_minutes;
    public $next_dial_my_callbacks;
    public $scheduled_callbacks_timezones_container;
    public $scheduled_callbacks_auto_reschedule;
    public $scheduled_callbacks;
    public $scheduled_callbacks_email_alert;
    public $callback_active_limit_override;
    public $scheduled_callbacks_force_dial;
    public $drop_call_seconds;
    public $drop_action;
    public $safe_harbor_exten;
    public $safe_harbor_audio;
    public $safe_harbor_audio_field;
    public $safe_harbor_menu_id;
    public $drop_inbound_group;
    public $disable_dispo_status;
    public $wrapup_seconds;
    public $wrapup_message;
    public $wrapup_bypass;
    public $wrapup_after_hotkey;
    public $script_top_dispo;
    Public $am_message_exten;
    Public $dead_trigger_action;
    Public $dead_trigger_seconds;
    Public $dead_trigger_repeat;
    Public $dead_max;
    Public $campaign3;



    public function get_campaign($id)
    {
        global $conn;

        $sql = "Select * from vicidial_campaigns where campaign_id =" . $id;
        $result = mysqli_query($conn, $sql);
        return $result;
    }


}
